use std::env;
use std::fs;
use std::path::PathBuf;

const TYPESCRIPT_VERSION: &str = "5.9.3";
const LIB_DIR: &str = "fixtures/typescript-libs";

fn main() {
  let bundled_enabled = env::var_os("CARGO_FEATURE_BUNDLED_LIBS").is_some();
  let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
  let lib_dir = manifest_dir.join(LIB_DIR).join(TYPESCRIPT_VERSION);

  // Only scan the vendored lib directory when the `bundled-libs` feature is
  // enabled. This keeps builds that opt-out of bundling lightweight and allows
  // consuming the crate without needing to ship the TypeScript fixture files.
  if !bundled_enabled {
    let mut output = String::new();
    output.push_str("// @generated by build.rs - do not edit.\n");
    output.push_str(&format!(
      "pub const TYPESCRIPT_VERSION: &str = {:?};\n",
      TYPESCRIPT_VERSION
    ));
    output.push_str("pub const LIBS: &[(&str, &str)] = &[];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("typescript_libs_generated.rs"), output)
      .expect("write generated typescript libs");
    return;
  }

  println!("cargo:rerun-if-changed={}", lib_dir.display());

  let mut libs: Vec<String> = Vec::new();
  for entry in fs::read_dir(&lib_dir).unwrap_or_else(|err| {
    panic!(
      "failed to read TypeScript lib dir {}: {err}",
      lib_dir.display()
    )
  }) {
    let entry = entry.expect("read_dir entry");
    let path = entry.path();
    if !path.is_file() {
      continue;
    }
    let Some(name) = path.file_name().and_then(|s| s.to_str()) else {
      continue;
    };
    if !(name.starts_with("lib.") && name.ends_with(".d.ts")) {
      continue;
    }
    println!("cargo:rerun-if-changed={}", path.display());
    libs.push(name.to_string());
  }

  libs.sort();

  let mut output = String::new();
  output.push_str("// @generated by build.rs - do not edit.\n");
  output.push_str(&format!(
    "pub const TYPESCRIPT_VERSION: &str = {:?};\n",
    TYPESCRIPT_VERSION
  ));
  output.push_str("pub const LIBS: &[(&str, &str)] = &[\n");
  for lib in libs {
    output.push_str(&format!(
      "  ({0:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{1}/{2}/{0}\"))),\n",
      lib, LIB_DIR, TYPESCRIPT_VERSION
    ));
  }
  output.push_str("];\n");

  let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
  fs::write(out_dir.join("typescript_libs_generated.rs"), output)
    .expect("write generated typescript libs");
}
