#![deny(missing_debug_implementations)]

mod display;
mod eval;
mod ids;
mod kind;
mod options;
mod relate;
mod shape;
mod signature;
mod store;

pub use display::TypeDisplay;
pub use eval::ExpandedType;
pub use eval::TypeEvaluator;
pub use eval::TypeExpander;
pub use ids::DefId;
pub use ids::NameId;
pub use ids::ObjectId;
pub use ids::ShapeId;
pub use ids::SignatureId;
pub use ids::TypeId;
pub use ids::TypeParamId;
pub use kind::MappedModifier;
pub use kind::MappedType;
pub use kind::TemplateChunk;
pub use kind::TemplateLiteralType;
pub use kind::TupleElem;
pub use kind::TypeKind;
pub use options::TypeOptions;
pub use relate::RelateCtx;
pub use relate::RelateHooks;
pub use relate::RelateTypeExpander;
pub use relate::RelationKind;
pub use relate::RelationMode;
pub use relate::RelationResult;
pub use shape::Accessibility;
pub use shape::Indexer;
pub use shape::ObjectType;
pub use shape::PropData;
pub use shape::PropKey;
pub use shape::Property;
pub use shape::Shape;
pub use signature::Param;
pub use signature::Signature;
pub use store::PrimitiveIds;
pub use store::TypeStore;
