#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")" >/dev/null

npx prettier@2.3.2 -w 'version' '.github/**/*.yaml' 'minify-js-nodejs/*.{js,json,ts}'

# Nightly is required because .rustfmt.toml uses unstable options (e.g. wrap_comments).
cargo +nightly fmt

popd >/dev/null
