#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
output="${repo_root}/docs/deps.md"

python3 - <<'PY' "${repo_root}" "${output}"
import json
import pathlib
import re
import subprocess
import sys

repo_root = pathlib.Path(sys.argv[1])
output = pathlib.Path(sys.argv[2])

metadata = json.loads(
    subprocess.check_output(
        ["cargo", "metadata", "--format-version", "1", "--no-deps"],
        cwd=repo_root,
    )
)

workspace_ids = set(metadata["workspace_members"])
packages = {pkg["id"]: pkg for pkg in metadata["packages"]}
workspace_names = {packages[pid]["name"] for pid in workspace_ids}

edges = set()
for pid in workspace_ids:
    pkg = packages[pid]
    source = pkg["name"]
    for dep in pkg.get("dependencies", []):
        # Only keep workspace edges (path dependencies with a known workspace name).
        if not dep.get("path"):
            continue
        target = dep["name"]
        if target in workspace_names:
            edges.add((source, target))

def mermaid_id(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", name)

nodes = sorted(workspace_names)
edges = sorted(edges)

lines = []
lines.append("# Workspace dependency graph")
lines.append("")
lines.append("_Generated by `scripts/gen_deps_graph.sh`. Do not edit manually._")
lines.append("")
lines.append("Run `./scripts/gen_deps_graph.sh` (or `just docs`) to refresh.")
lines.append("")
lines.append("```mermaid")
lines.append("graph TD")
for name in nodes:
    lines.append(f'    {mermaid_id(name)}["{name}"]')
for a, b in edges:
    lines.append(f"    {mermaid_id(a)} --> {mermaid_id(b)}")
lines.append("```")
lines.append("")
lines.append("Workspace-only edges are shown; third-party dependencies are omitted.")

output.write_text("\n".join(lines) + "\n")
PY

echo "Updated ${output}"
